volumes:
    database-volumes:

services:
  database: 
    image: postgres
    container_name: postgresql
    network_mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - '5433:5432'
    volumes:
      - 'database-volumes:/var/lib/postgresql/data'