version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    ports: 
      - 9100:9100
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports: 
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana


  postgres-exporter: 
    container_name: postgres-exporter
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    ports: 
      - 9187:9187
    environment:
      - DATA_SOURCE_URI=postgres:5432/postgres?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=postgres

  faz-o-pix:
    container_name: faz-o-pix
    image: mywallet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_QUEUENAME=payments
  
  migrate:
    container_name: faz-o-pix-migrate
    image: mywallet-migrate
    build:
      context: .
      dockerfile: Dockerfile.migrations

  rabbitmq:
    image: rabbitmq:3.12.12-management
    ports: 
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq

  psp-api:
    container_name: psp-mock
    image: vitorluizms/psp-mock:2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"


volumes:
  grafana:
  postgres:
  rabbitmq-volume: