version: '3.8'
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    network_mode: host
    ports: 
      - 9100:9100
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    network_mode: host
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    network_mode: host
    ports: 
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana

  postgres-exporter: 
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    network_mode: host
    ports: 
      - 9187:9187
    environment:
      - DATA_SOURCE_URI=192.168.1.7:5432/dev?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=postgres

volumes:
  grafana: